### ISSUE TITLE
datepicker 

### ISSUE THREAD

**Issue by rlorxl** [Anjiwoong/React-Tmoney-Bus#26]
## ISSUE

**Problem**
- input type='date'로 만든 기본 datepicker를 사용해 날짜를 설정하고 dispatch
→  store에 업데이트는 가능한데 view에 지정한 date value가 그려지지 않음. 같은 날짜를 두번눌러야 변경됨.
→  react datepicker 라이브러리로 시도 ( 미해결. 같은 문제 발생함 )

**Comment by Anjiwoong** [comment]
terminalContext로 일단 해결 . 왜 그런 문제가 발생했는지에 대해서는 좀더 찾아봐야 함
